# Exercise 13: Basic Probability

Given the joint probability distribution `JointPDF[x][y][z]` of a binary variable $X$,  a three-valued variable $Y$, and a binary variable $Z$ perform the following computations:

In [15]:
import numpy as np
JointPDF = np.array(
    [
        [
            [0.1, 0.05],
            [0.11, 0.12],
            [0.07,0.03]
        ],
        [
            [0.06, 0.16],
            [0.01, 0.08],
            [0.19,0.02]
        ]
     ]
     )

1. Verify that `JointPDF` is normalised.

In [13]:
JointPDF.sum(axis=(0,1,2))

1.0

2. Compute $P(X)$, $P(Y)$ and $P(Z)$

In [16]:
# Sum over the other axes
PX = JointPDF.sum(axis=(1,2))
PY = JointPDF.sum(axis=(0,2))
PZ = JointPDF.sum(axis=(0,1))

print(PX)
print(PY)
print(PZ)

[0.48 0.52]
[0.37 0.32 0.31]
[0.54 0.46]


3. Compute $P(X,Y)$, $P(Y,Z)$, $P(X,Z)$

In [18]:
PXY = JointPDF.sum(axis=2)
PXZ = JointPDF.sum(axis=1)
PYZ = JointPDF.sum(axis=0)
print(PXY)
print(PXZ)
print(PYZ)

[[0.15 0.23 0.1 ]
 [0.22 0.09 0.21]]
[[0.28 0.2 ]
 [0.26 0.26]]
[[0.16 0.21]
 [0.12 0.2 ]
 [0.26 0.05]]


4. Compute $P(X\vert Y)

In [35]:

PX_y0 = PXY[:,0]/PXY[:,0].sum()
PX_y1 = PXY[:,1]/PXY[:,1].sum()
PX_y2 = PXY[:,2]/PXY[:,2].sum()


print(PX_y0)
print(PX_y1)
print(PX_y2)

[0.40540541 0.59459459]
[0.71875 0.28125]
[0.32258065 0.67741935]
